# Generated by Django 2.2.5 on 2022-01-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_delete_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileList',
        ),
    ]
