# Generated by Django 2.2.5 on 2022-01-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_no', models.AutoField(primary_key=True, serialize=False)),
                ('member_email', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=10)),
                ('member_password', models.CharField(max_length=20)),
                ('member_joindate', models.DateTimeField()),
                ('admin_flag', models.IntegerField(default=0)),
                ('member_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
