# Generated by Django 2.2.5 on 2022-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('algo_no', models.AutoField(primary_key=True, serialize=False)),
                ('algo_update', models.DateField()),
                ('algo_title', models.CharField(max_length=50)),
                ('algo_detail', models.TextField()),
            ],
            options={
                'db_table': 'algorithm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlgorithmImage',
            fields=[
                ('image_no', models.AutoField(primary_key=True, serialize=False)),
                ('image_root', models.CharField(max_length=1000)),
                ('image_name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'algorithm_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
    ]
