# Generated by Django 2.2.5 on 2022-01-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('algo_no', models.AutoField(primary_key=True, serialize=False)),
                ('algo_update', models.DateTimeField()),
                ('algo_title', models.CharField(max_length=50)),
                ('algo_detail', models.TextField()),
            ],
            options={
                'db_table': 'algorithm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlgorithmImage',
            fields=[
                ('image_no', models.AutoField(primary_key=True, serialize=False)),
                ('image_root', models.CharField(max_length=1000)),
                ('image_name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'algorithm_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment_detail', models.TextField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('likes_no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('sol_no', models.AutoField(primary_key=True, serialize=False)),
                ('sol_detail', models.TextField()),
                ('sol_like', models.IntegerField()),
            ],
            options={
                'db_table': 'solution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
    ]
