# Generated by Django 2.2.5 on 2022-01-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Algorithm',
        ),
    ]
