# Generated by Django 2.2.5 on 2022-01-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.DeleteModel(
            name='AlgorithmImage',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
