# Generated by Django 2.2.5 on 2022-01-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0002_delete_algorithm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgorithmImage',
        ),
    ]
